clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
    - open-cluster-management
    - vault
    - external-secrets-operator:
        operatorGroup: true
        targetNamespaces: []
    - external-secrets
    - openshift-nfd
    - nvidia-gpu-operator
    - redhat-ods-operator:
        operatorGroup: true
        targetNamespaces: []
    - ai-agent:
        operatorGroup: true
        targetNamespaces:
          - ai-agent
        labels:
          opendatahub.io/dashboard: "true"
          modelmesh-enabled: 'false'
    - openshift-serverless:
        operatorGroup: true
        targetNamespaces: []
    - agent-monitoring

  subscriptions:
    nfd:
      name: nfd
      namespace: openshift-nfd
    nvidia:
      name: gpu-operator-certified
      namespace: nvidia-gpu-operator
      source: certified-operators
    serverless:
      name: serverless-operator
      namespace: openshift-serverless
    servicemesh:
      name: servicemeshoperator
      namespace: openshift-operators
    rhoai:
      name: rhods-operator
      namespace: redhat-ods-operator
    eso:
      name: openshift-external-secrets-operator
      namespace: external-secrets-operator
      channel: stable-v1

  projects:
    - hub
    - ai-agent
    - agent-monitoring
    - gpu-config
    - openshift-ai

  sharedValueFiles:
    - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml'

  applications:
    vault:
      name: vault
      namespace: vault
      project: hub
      chart: hashicorp-vault
      chartVersion: 0.1.*
    openshift-external-secrets:
      name: openshift-external-secrets
      namespace: external-secrets
      project: hub
      chart: openshift-external-secrets
      chartVersion: 0.0.*
    vllm-inference-service:
      name: vllm-inference-service
      namespace: ai-agent
      project: hub
      path: charts/all/vllm-inference-service
      syncPolicy:
        automated:
          selfHeal: true
        retry:
          limit: 20
    pgvector:
      name: pgvector
      namespace: ai-agent
      project: ai-agent
      path: charts/all/pgvector
    sample-api:
      name: sample-api
      namespace: ai-agent
      project: ai-agent
      path: charts/all/sample-api
    bee-agent-service:
      name: bee-agent-service
      namespace: ai-agent
      project: ai-agent
      path: charts/all/bee-agent-service
    agent-chat-ui:
      name: agent-chat-ui
      namespace: ai-agent
      project: ai-agent
      path: charts/all/agent-chat-ui
    agent-monitoring:
      name: agent-monitoring
      namespace: agent-monitoring
      project: agent-monitoring
      kustomize: true
      path: charts/all/agent-monitoring/kustomize/overlays/dev
    nfd-config:
      name: nfd-config
      namespace: openshift-cfd
      project: gpu-config
      path: charts/all/nfd-config
    nvidia-config:
      name: nvidia-config
      namespace: nvidia-network-operator
      project: gpu-config
      path: charts/all/nvidia-gpu-config
    agent-ui-config:
      name: agent-ui-config
      namespace: ai-agent
      project: gpu-config
      path: charts/all/agent-ui-config
    agent-monitoring-config:
      name: agent-monitoring-config
      namespace: agent-monitoring
      project: gpu-config
      path: charts/all/agent-monitoring-config
    openshift-ai:
      name: openshift-ai
      namespace: redhat-ods-operator
      project: openshift-ai
      path: charts/all/rhods
