apiVersion: v1
kind: Service
metadata:
  name: agent-chat-ui
  labels:
    app.kubernetes.io/name: agent-chat-ui
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: agent-chat-ui
