apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: huggingface-secret
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: huggingface-secret
    creationPolicy: Owner
  data:
    - secretKey: hftoken
      remoteRef:
        key: secret/data/hub/hfmodel
        property: hftoken
